name: Release

on:
  push:
    tags: ["v*"]

env:
  CARGO_TERM_COLOR: always
  BIN_NAME: npkill-rs

jobs:
  build:
    name: Build ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            ext: tar.gz
            pack: tar czf
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            ext: tar.gz
            pack: tar czf
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            ext: zip
            pack: 7z a -tzip
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}
      - name: Package binary (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          ${{ matrix.pack }} ../../../${{ env.BIN_NAME }}-${{ matrix.target }}.${{ matrix.ext }} ${{ env.BIN_NAME }}
      - name: Package binary (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          cd target/${{ matrix.target }}/release
          7z a -tzip ../../../${{ env.BIN_NAME }}-${{ matrix.target }}.zip ${{ env.BIN_NAME }}.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: ${{ env.BIN_NAME }}-${{ matrix.target }}.${{ matrix.ext }}

  release:
    name: Publish Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Collect artifacts and checksums
        run: |
          mkdir release_assets
          find artifacts -name "*.tar.gz" -o -name "*.zip" -exec cp {} release_assets/ \;
          cd release_assets
          sha256sum * > sha256sums.txt
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release_assets/*
          generate_release_notes: true
